certificate:
  enabled: true
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
ingressRoute:
  enabled: true
secret:
  create: false
image:
  pullPolicy: IfNotPresent
  tag: b06122f-25500483630-1
