onePasswordSecrets:
  vault: google-ads-mcp
  manualItem: google-ads-mcp_production-manual
autoscaling:
  enabled: true
host: mcp-google-ads.stape.io
image:
  repository: europe-west1-docker.pkg.dev/stape-production/stape/google-ads-mcp
  tag: 3564559-37910095559-1
resources:
  requests:
    cpu: 150m
    memory: 300Mi
